// (c) Meta Platforms, Inc. and affiliates. Confidential and proprietary.
#ifndef OVR_Audio_Defaults_h
#define OVR_Audio_Defaults_h

#define OVRA_DEFAULT_VOICE_LIMIT (64)
#define OVRA_VOICE_LIMIT_MINIMUM (1)
#define OVRA_VOICE_LIMIT_MAXIMUM (1024)

#define OVRA_COORDINATE_MAXIMUM (1.e+20f)

#define OVRA_UNIT_SCALE_MINIMUM (0.001f)
#define OVRA_UNIT_SCALE_MAXIMUM (1000.0f)
#define OVRA_DEFAULT_UNIT_SCALE (1.0f)

#define OVRA_ATTENUATION_RANGE_MINIMUM (0.0f)
#define OVRA_ATTENUATION_RANGE_MAXIMUM (10000.0f)
#define OVRA_DEFAULT_ATTENUATION_RANGE_MINIMUM (1.0f)
#define OVRA_DEFAULT_ATTENUATION_RANGE_MAXIMUM (400.0f)

#define OVRA_HRTF_INTENSITY_MINIMUM (0.0f)
#define OVRA_HRTF_INTENSITY_MAXIMUM (1.0f)
#define OVRA_DEFAULT_HRTF_INTENSITY (1.0f)

#define OVRA_SHARED_REFLECTIONS_SEND_GAIN_MINIMUM (0.001f)
#define OVRA_SHARED_REFLECTIONS_SEND_GAIN_MAXIMUM (10.0f)
#define OVRA_DEFAULT_SHARED_REFLECTIONS_SEND_GAIN (1.0f)

#define OVRA_SHARED_REVERB_SEND_GAIN_MINIMUM (0.001f)
#define OVRA_SHARED_REVERB_SEND_GAIN_MAXIMUM (10.0f)
#define OVRA_DEFAULT_SHARED_REVERB_SEND_GAIN (1.0f)

#define OVRA_DIRECTIVITY_INTENSITY_MINIMUM (0.0f)
#define OVRA_DIRECTIVITY_INTENSITY_MAXIMUM (1.0f)
#define OVRA_DEFAULT_DIRECTIVITY_INTENSITY (1.0f)

#define OVRA_OCCLUSION_INTENSITY_MINIMUM (0.0f)
#define OVRA_OCCLUSION_INTENSITY_MAXIMUM (1.0f)
#define OVRA_DEFAULT_OCCLUSION_INTENSITY (1.0f)

#define OVRA_REVERB_REACH_MINIMUM (0.0f)
#define OVRA_REVERB_REACH_MAXIMUM (1.0f)
#define OVRA_DEFAULT_REVERB_REACH (0.5f)

#define OVRA_RADIUS_MINIMUM (0.0f)
#define OVRA_RADIUS_MAXIMUM (1000.0f)
#define OVRA_DEFAULT_RADIUS (0.0f)

#define OVRA_ROOM_SIZE_MINIMUM (0.0f)
#define OVRA_ROOM_SIZE_MAXIMUM (200.0f)
#define OVRA_DEFAULT_ROOM_SIZE_X (8.0f)
#define OVRA_DEFAULT_ROOM_SIZE_Y (3.0f)
#define OVRA_DEFAULT_ROOM_SIZE_Z (5.0f)

#define OVRA_ROOM_REFLECT_MINIMUM (0.0f)
#define OVRA_ROOM_REFLECT_MAXIMUM (0.97f)
#define OVRA_DEFAULT_ROOM_REFLECT_LEFT (0.9f)
#define OVRA_DEFAULT_ROOM_REFLECT_RIGHT (0.9f)
#define OVRA_DEFAULT_ROOM_REFLECT_UP (0.9f)
#define OVRA_DEFAULT_ROOM_REFLECT_DOWN (0.9f)
#define OVRA_DEFAULT_ROOM_REFLECT_BACK (0.9f)
#define OVRA_DEFAULT_ROOM_REFLECT_FRONT (0.9f)

#define OVRA_REVERB_WET_MIX_MINIMUM (0.001f)
#define OVRA_REVERB_WET_MIX_MAXIMUM (10.0f)
#define OVRA_DEFAULT_REVERB_WET_MIX (1.0f)

#define OVRA_CONTROL_ZONE_REVERB_LEVEL_MINIMUM (-60.0f)
#define OVRA_CONTROL_ZONE_REVERB_LEVEL_MAXIMUM (60.0f)
#define OVRA_CONTROL_ZONE_RT60_MINIMUM (-10.0f)
#define OVRA_CONTROL_ZONE_RT60_MAXIMUM (10.0f)
#define OVRA_CONTROL_ZONE_REFLECTION_TIME_MINIMUM (0.01f)
#define OVRA_CONTROL_ZONE_REFLECTION_TIME_MAXIMUM (10.0f)

#endif // OVR_Audio_Defaults_h
